name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Set up NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: yarn

      - name: Install dependencies
        run: yarn --immutable

      - name: Run build
        run: yarn build

      - name: Run lint
        run: yarn lint

      - name: Run tests
        run: yarn test

  #    - name: Codecov upload
  #      uses: codecov/codecov-action@v3.1.1
  #      with:
  #        token: ${{ secrets.CODECOV_TOKEN }}
  #        directory: coverage/
  #        fail_ci_if_error: true
